INSERT INTO Competition VALUES (1, 'Superkonkurransen', 'False');
INSERT INTO Competition VALUES (2, 'Drittkonkurransen', 'False');
INSERT INTO Competition VALUES (3, 'OKkonkurransen', 'False');

INSERT INTO Archetype VALUES ('Løp');
INSERT INTO Archetype VALUES ('Kast');
INSERT INTO Archetype VALUES ('Langhopp');
INSERT INTO Archetype VALUES ('Høydehopp');

INSERT INTO Discipline VALUES ('Spyd', 'Kast', 'Spydkast');
INSERT INTO Discipline VALUES ('Lengde', 'Langhopp', 'Lengdehopp');
INSERT INTO Discipline VALUES ('Høyde', 'Høydehopp');
INSERT INTO Discipline VALUES ('Tresteg', 'Langhopp');
INSERT INTO Discipline VALUES ('Kule', 'Kast', 'Kulestøt');
INSERT INTO Discipline VALUES ('Liten ball', 'Kast');
INSERT INTO Discipline VALUES ('Diskos', 'Kast', 'Diskoskast');
INSERT INTO Discipline VALUES ('Slegge', 'Kast');
INSERT INTO Discipline VALUES ('100m', 'Løp');
INSERT INTO Discipline VALUES ('200m', 'Løp');
INSERT INTO Discipline VALUES ('400m', 'Løp');
INSERT INTO Discipline VALUES ('800m', 'Løp');
INSERT INTO Discipline VALUES ('1500m', 'Løp');
INSERT INTO Discipline VALUES ('5000m', 'Løp');
INSERT INTO Discipline VALUES ('10 000m', 'Løp');
INSERT INTO Discipline VALUES ('110m hk', 'Løp');
INSERT INTO Discipline VALUES ('100m hk', 'Løp');
INSERT INTO Discipline VALUES ('60m', 'Løp');
INSERT INTO Discipline VALUES ('80m', 'Løp');
INSERT INTO Discipline VALUES ('600m', 'Løp');
INSERT INTO Discipline VALUES ('Stav',  'Høydehopp', 'Stavsprang');

INSERT INTO CompetitorClass VALUES ('G-10');
INSERT INTO CompetitorClass VALUES ('G-11');
INSERT INTO CompetitorClass VALUES ('G-12');
INSERT INTO CompetitorClass VALUES ('G-13');
INSERT INTO CompetitorClass VALUES ('G-14');
INSERT INTO CompetitorClass VALUES ('G-15');
INSERT INTO CompetitorClass VALUES ('G-16');
INSERT INTO CompetitorClass VALUES ('G-17');
INSERT INTO CompetitorClass VALUES ('G-18/19');
INSERT INTO CompetitorClass VALUES ('MJ');
INSERT INTO CompetitorClass VALUES ('MS');

INSERT INTO CompetitorClass VALUES ('J-10');
INSERT INTO CompetitorClass VALUES ('J-11');
INSERT INTO CompetitorClass VALUES ('J-12');
INSERT INTO CompetitorClass VALUES ('J-13');
INSERT INTO CompetitorClass VALUES ('J-14');
INSERT INTO CompetitorClass VALUES ('J-15');
INSERT INTO CompetitorClass VALUES ('J-16');
INSERT INTO CompetitorClass VALUES ('J-17');
INSERT INTO CompetitorClass VALUES ('J-18/19');
INSERT INTO CompetitorClass VALUES ('KJ');
INSERT INTO CompetitorClass VALUES ('KS');

INSERT INTO Discipline_Class VALUES ('Spyd', 'G-12', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-13', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-14', '600g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-15', '600g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-16', '700g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-17', '700g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-18/19', '800g spyd'); 
INSERT INTO Discipline_Class VALUES ('Spyd', 'MJ', '800g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'MS', '800g spyd');

INSERT INTO Discipline_Class VALUES ('Spyd', 'J-12', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'J-13', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'J-14', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'J-15', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'J-16', '600g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'J-17', '600g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'J-18/19', '600g spyd'); 
INSERT INTO Discipline_Class VALUES ('Spyd', 'KJ', '600g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'KS', '600g spyd');

INSERT INTO Discipline_Class VALUES ('Kule', 'G-12', '2kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'G-13', '3kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'G-14', '3kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'G-15', '4kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'G-16', '4kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'G-17', '5kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'G-18/19', '6kg kule'); 
INSERT INTO Discipline_Class VALUES ('Kule', 'MJ', '7,26kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'MS', '7,26 kule');

INSERT INTO Discipline_Class VALUES ('Kule', 'J-12', '2kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'J-13', '2kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'J-14', '2kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'J-15', '2kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'J-16', '3lg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'J-17', '3kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'J-18/19', '4kg kule'); 
INSERT INTO Discipline_Class VALUES ('Kule', 'KJ', '4kg kule');
INSERT INTO Discipline_Class VALUES ('Kule', 'KS', '4kg kule');

INSERT INTO Discipline_Class VALUES ('Lengde', 'G-12', '0,5m satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'G-13', '0,5m satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'G-14', '0,5m satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'G-15', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'G-16', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'G-17', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'G-18/19', 'Ingen satssone'); 
INSERT INTO Discipline_Class VALUES ('Lengde', 'MJ', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'MS', 'Ingen satssone');

INSERT INTO Discipline_Class VALUES ('Lengde', 'J-12', '0,5m satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'J-13', '0,5m satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'J-14', '0,5m satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'J-15', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'J-16', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'J-17', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'J-18/19', 'Ingen satssone'); 
INSERT INTO Discipline_Class VALUES ('Lengde', 'KJ', 'Ingen satssone');
INSERT INTO Discipline_Class VALUES ('Lengde', 'KS', 'Ingen satssone');
