INSERT INTO Competition VALUES (1, 'Superkonkurransen', 'False');
INSERT INTO Competition VALUES (2, 'Drittkonkurransen', 'False');
INSERT INTO Competition VALUES (3, 'OKkonkurransen', 'False');

INSERT INTO Discipline VALUES ('Spyd', 'Spydkast');
INSERT INTO Discipline VALUES ('Lengde', 'Lengdehopp');
INSERT INTO Discipline VALUES ('Høyde', 'Høydehopp');
INSERT INTO Discipline VALUES ('Tresteg');
INSERT INTO Discipline VALUES ('Kule', 'Kulestøt');
INSERT INTO Discipline VALUES ('Liten ball');
INSERT INTO Discipline VALUES ('Diskos', 'Diskoskast');
INSERT INTO Discipline VALUES ('Slegge');
INSERT INTO Discipline VALUES ('100m');
INSERT INTO Discipline VALUES ('200m');
INSERT INTO Discipline VALUES ('400m');
INSERT INTO Discipline VALUES ('800m');
INSERT INTO Discipline VALUES ('1500m');
INSERT INTO Discipline VALUES ('5000m');
INSERT INTO Discipline VALUES ('10 000m');
INSERT INTO Discipline VALUES ('110m hk');
INSERT INTO Discipline VALUES ('100m hk');
INSERT INTO Discipline VALUES ('60m');
INSERT INTO Discipline VALUES ('80m');
INSERT INTO Discipline VALUES ('600m');
INSERT INTO Discipline VALUES ('Stav', 'Stavsprang');

INSERT INTO CompetitorClass VALUES ('MS');
INSERT INTO CompetitorClass VALUES ('MJ');
INSERT INTO CompetitorClass VALUES ('KJ');
INSERT INTO CompetitorClass VALUES ('KS');
INSERT INTO CompetitorClass VALUES ('G-10');
INSERT INTO CompetitorClass VALUES ('G-11');
INSERT INTO CompetitorClass VALUES ('G-12');
INSERT INTO CompetitorClass VALUES ('G-13');
INSERT INTO CompetitorClass VALUES ('G-14');
INSERT INTO CompetitorClass VALUES ('G-15');
INSERT INTO CompetitorClass VALUES ('G-16');
INSERT INTO CompetitorClass VALUES ('G-17');
INSERT INTO CompetitorClass VALUES ('G-18/19');
INSERT INTO CompetitorClass VALUES ('MJ');
INSERT INTO CompetitorClass VALUES ('MS');

INSERT INTO CompetitorClass VALUES ('J-18/19');
INSERT INTO CompetitorClass VALUES ('J-17');
INSERT INTO CompetitorClass VALUES ('J-16');
INSERT INTO CompetitorClass VALUES ('J-15');
INSERT INTO CompetitorClass VALUES ('J-14');
INSERT INTO CompetitorClass VALUES ('J-13');
INSERT INTO CompetitorClass VALUES ('J-12');
INSERT INTO CompetitorClass VALUES ('J-11');
INSERT INTO CompetitorClass VALUES ('J-10');

INSERT INTO Discipline_Class VALUES ('Spyd', 'G-12', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-13', '400g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-14', '600g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-15', '600g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-16', '700g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-17', '700g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'G-18/19', '800g spyd'); 
INSERT INTO Discipline_Class VALUES ('Spyd', 'MJ', '800g spyd');
INSERT INTO Discipline_Class VALUES ('Spyd', 'MS', '800g spyd');
